import { type ReactNode } from 'react';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import { dir } from 'i18next';
import i18nConfig from '@root/i18nConfig';
import Navigation from '~/components/nav';
import '~/styles/globals.css';
import { TRPCReactProvider } from '~/trpc/react';

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-sans',
});

export const metadata = {
    title: 'Voucher Example',
    description: 'Generated by create-t3-app',
    icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export function generateStaticParams() {
    return i18nConfig.locales.map((locale) => ({ locale }));
}

export default function RootLayout({
    children,
    params: { locale },
}: {
    children: ReactNode;
    params: { locale: string };
}) {
    return (
        <html lang={locale} dir={dir(locale)}>
            <body
                className={`flex flex-col h-screen bg-gray-900 font-sans ${inter.variable} text-white`}
            >
                <TRPCReactProvider cookies={cookies().toString()}>
                    <Navigation locale={locale} />

                    {children}
                </TRPCReactProvider>
            </body>
        </html>
    );
}
